#pragma config(Sensor, S4,     color,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main(){
	while (true){
		displaySensorValues(1, S4);
			if(SensorValue(S4) > 170& SensorValue(S4)<110)
			{
				displayText(line2, "Green");
			}
			if(SensorValue(S4) > 40 & SensorValue(S4)<10)
			{
			displayText(line2, "Red");
			}
			if(SensorValue(S4) > 290 & SensorValue(S4) < 200)
			{
				displayText(line2, "Blue");
			}
			if(SensorValue(S4) > 100 & SensorValue(S4) < 50)
			{
				displayText(line2, "Yellow");
			}
	}

}
