#pragma config(Sensor, S4,     Color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



int Cvet;//Peremennaya INT
int colordetect(){//Finkciya vozvrawaet int
	Cvet = 0;
int hue = getColorHue(S4);
if(hue > 0 & hue < 30){
  Cvet = 5;	//Red
}
if(hue> 300 & hue < 360){
	Cvet =5;//Red
}
if(hue > 10 & hue< 90){
	Cvet = 4;	//Yellow
}
if(hue > 180 & hue < 260){
	Cvet = 3; // Blue
}
if (hue > 90 & hue < 150){
	Cvet = 2; // Green
}
return Cvet;//tut on vernul int
}
task main()
{
while(true){
colordetect();
displayVariableValues(line1, Cvet);
}
}
