#pragma config(Sensor, S2,     color,          sensorEV3_Color)
#pragma config(Sensor, S3,     color,          sensorEV3_Color)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void pdreg (int ss1, int ss2, int speed, float kp, float kd){
	int delta = ss1 - ss2;
	int pc = kp * delta;
	int deltaold;
	int dc = (delta - deltaold) * kd;
	int U = pc + dc;
	setMotorSpeed(motorB, speed + U);
	setMotorSpeed(motorC, (speed - U)*(-1));
	delta = deltaold;
	}

void tocross(){
		while(getColorReflected(S2) + getColorReflected(S3)>40){
pdreg(getColorReflected(S2), getColorReflected(S3), 30, 0.2, 0.4);
}
}


	task main(){
		while (true){
			tocross()
}
}
