#pragma config(Sensor, S2,     color,          sensorEV3_Color)
#pragma config(Sensor, S3,     color,          sensorEV3_Color)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



// kp == 0.1 , kd == 0.2 (middle motors)



void pdreg (int speed, float kp, float kd){  //PDregulator inputs:(S1,S2, speed, kp, kd)
	int delta = getColorReflected(S2) - getColorReflected(S3);
	int pc = kp * delta;
	int deltaold;
	int dc = (delta - deltaold) * kd;
	int U = pc + dc;
	setMotorSpeed(motorB, speed + U);
	setMotorSpeed(motorC, (speed - U)*(-1));
	delta = deltaold;
	}




void enclinemove (int espeed, int edegrees){
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
while (getMotorEncoder(motorB) < edegrees){
	pdreg(espeed, 0.1, 0.2);


	}

}



void tocross (int tspeed, int tdegr){
	while (getColorReflected(S2) + getColorReflected(S3) > tdegr){
			pdreg(tspeed, 0.1, 0.2);



	}
enclinemove(tspeed, tdegr);
}




// kp 0.1
//kd 0.2
//speed 30


task main () {

tocross(30, 100);

}
